version: '3'

services:
  app:
    image: overlogic/overpress:${OVERPRESS_IMAGE}
    deploy:
      placement:
        constraints:
          - "node.type==${NODE_TYPE}"
          - "node.app==${NODE_APP}"
      resources:
        limits:
          memory: ${APP_MEM_LIMIT}
    volumes:
      - app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_MEMORY_LIMIT: ${WP_MEM_LIMIT}
    links:
      - db:mysql
  db:
    image: mariadb:${MARIADB_IMAGE}
    deploy:
      placement:
        constraints:
          - "node.type==${NODE_TYPE}"
          - "node.app==${NODE_APP}"
      resources:
        limits:
          memory: ${DB_MEM_LIMIT}
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "!Str0ngP@ssword%"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  web:
    hostname: ${HOSTNAME}
    image: nginx:${NGINX_IMAGE}
    deploy:
      placement:
        constraints:
          - "node.type==${NODE_TYPE}"
          - "node.app==${NODE_APP}"
    volumes:
      - ./nginx/ol_op_nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - app:/var/www/html
    networks:
      - proxy-tier
      - default
    links:
      - app
    ports:
      - 80

volumes:
  db:
  app:

networks:
  proxy-tier:
    external:
      name: npm_npm-net
